// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: proto/moderator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Moderator_PromoteToModerator_FullMethodName = "/api.Moderator/PromoteToModerator"
	Moderator_DemoteToUser_FullMethodName       = "/api.Moderator/DemoteToUser"
)

// ModeratorClient is the client API for Moderator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ModeratorClient interface {
	PromoteToModerator(ctx context.Context, in *ModeratorRequest, opts ...grpc.CallOption) (*ModeratorResponse, error)
	DemoteToUser(ctx context.Context, in *ModeratorRequest, opts ...grpc.CallOption) (*ModeratorResponse, error)
}

type moderatorClient struct {
	cc grpc.ClientConnInterface
}

func NewModeratorClient(cc grpc.ClientConnInterface) ModeratorClient {
	return &moderatorClient{cc}
}

func (c *moderatorClient) PromoteToModerator(ctx context.Context, in *ModeratorRequest, opts ...grpc.CallOption) (*ModeratorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModeratorResponse)
	err := c.cc.Invoke(ctx, Moderator_PromoteToModerator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *moderatorClient) DemoteToUser(ctx context.Context, in *ModeratorRequest, opts ...grpc.CallOption) (*ModeratorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModeratorResponse)
	err := c.cc.Invoke(ctx, Moderator_DemoteToUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ModeratorServer is the server API for Moderator service.
// All implementations must embed UnimplementedModeratorServer
// for forward compatibility.
type ModeratorServer interface {
	PromoteToModerator(context.Context, *ModeratorRequest) (*ModeratorResponse, error)
	DemoteToUser(context.Context, *ModeratorRequest) (*ModeratorResponse, error)
	mustEmbedUnimplementedModeratorServer()
}

// UnimplementedModeratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedModeratorServer struct{}

func (UnimplementedModeratorServer) PromoteToModerator(context.Context, *ModeratorRequest) (*ModeratorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PromoteToModerator not implemented")
}
func (UnimplementedModeratorServer) DemoteToUser(context.Context, *ModeratorRequest) (*ModeratorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DemoteToUser not implemented")
}
func (UnimplementedModeratorServer) mustEmbedUnimplementedModeratorServer() {}
func (UnimplementedModeratorServer) testEmbeddedByValue()                   {}

// UnsafeModeratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ModeratorServer will
// result in compilation errors.
type UnsafeModeratorServer interface {
	mustEmbedUnimplementedModeratorServer()
}

func RegisterModeratorServer(s grpc.ServiceRegistrar, srv ModeratorServer) {
	// If the following call pancis, it indicates UnimplementedModeratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Moderator_ServiceDesc, srv)
}

func _Moderator_PromoteToModerator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModeratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModeratorServer).PromoteToModerator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Moderator_PromoteToModerator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModeratorServer).PromoteToModerator(ctx, req.(*ModeratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Moderator_DemoteToUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModeratorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ModeratorServer).DemoteToUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Moderator_DemoteToUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ModeratorServer).DemoteToUser(ctx, req.(*ModeratorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Moderator_ServiceDesc is the grpc.ServiceDesc for Moderator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Moderator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Moderator",
	HandlerType: (*ModeratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PromoteToModerator",
			Handler:    _Moderator_PromoteToModerator_Handler,
		},
		{
			MethodName: "DemoteToUser",
			Handler:    _Moderator_DemoteToUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/moderator.proto",
}
