// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Commentary struct {
	CommentartyID  string  `json:"commentarty_id"`
	UserID         string  `json:"user_id"`
	Topic          string  `json:"topic"`
	Content        string  `json:"content"`
	CountLikes     int     `json:"count_likes"`
	ThemeID        string  `json:"theme_id"`
	Timestamp      string  `json:"timestamp"`
	MessageType    bool    `json:"message_type"`
	ReplyMessageID *string `json:"reply_message_id,omitempty"`
	TagID          *string `json:"tag_id,omitempty"`
}

type Mutation struct {
}

type Query struct {
}
